#!/bin/bash
set -e

#sv start socklog-unix || exit 1

source /etc/envvars

IP=`getent hosts ethereum-bootnode`
export BOOTSTRAP_IP=$(echo $IP | cut -d" " -f1)

exec 2>&1
exec geth --cache 2048 --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" ${NETWORKID:+"--networkid $NETWORKID"} ${BOOTNODES:+"--bootnodes $BOOTNODES"} --verbosity 3
